[agent]
  interval          = "10s"
  round_interval    = true
  flush_interval    = "10s"
  flush_jitter      = "2s"
  hostname          = "telegraf_gateway"
  omit_hostname     = false

[[outputs.influxdb_v2]]
  urls         = ["http://influxdb:8086"]
  token        = "${INFLUXDB_TOKEN}"
  organization = "traffic_org"
  bucket       = "vehicle_counts"

[[inputs.mqtt_consumer]]
  servers  = ["ssl://${HIVEMQ_HOST}:8883"]
  username = "${HIVEMQ_USER}"
  password = "${HIVEMQ_PASSWORD}"

  topics = [
    "traffic/counts",
    "traffic/status",
    "traffic/raw",
    "traffic/gateway",
  ]

  qos = 1

  client_id = "telegraf_tig_stack"

  topic_tag = "topic"

  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "traffic"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "node"
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "type"

    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "seq"
      type     = "uint"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "car"
      type     = "uint"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "truck"
      type     = "uint"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "bus"
      type     = "uint"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "motorcycle"
      type     = "uint"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "total"
      type     = "uint"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "fps"
      type     = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "heap"
      type     = "uint"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "uptime_s"
      type     = "uint"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "rssi"
      type     = "int"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "snr"
      type     = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "wifi_rssi"
      type     = "int"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "lora_rx_total"
      type     = "uint"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "mqtt_pub"
      type     = "uint"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path     = "mqtt_fail"
      type     = "uint"
      optional = true
