apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: traffic_org
      defaultBucket: vehicle_counts
    secureJsonData:
      token: $INFLUXDB_TOKEN
    isDefault: true
    editable: true
